name: PR Review - Crypto Finance Wallet Rest Server

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'dev'
    paths: 
      - 'applications/crypto-finance-wallet-rest-server/*'

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./applications/crypto-finance-wallet-rest-server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: 'Install Dependencies'
        run: |
          yarn install
          yarn build

      - name: 'Lint Check'
        run: yarn lint
          
      - name: 'Typescript Check'
        run: yarn tsc:check

      - name: Unit Test
        run: yarn test

      - name: E2E Test
        run: yarn test:e2e