name: PR Review

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "dev"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: "Install Dependencies"
        run: |
          yarn

      - name: "Lint Check"
        run: yarn lint

      - name: "Typescript Check"
        run: yarn tsc:check
